### ISSUE TITLE
composer not working properly 

### ISSUE THREAD

**Issue by ehsanmim** [opensheetorg/opensheet#2]
The composer install is not working in local. I guess there is problem with the initial commit. @emrecanful I think there might be a copy paste mistake in initial setup of the project.
![image](https://github.com/opensheetorg/opensheet/assets/115899665/b37ea4a8-ebf6-4ec7-8a1e-17a4a2936157)

**Comment by SudoFrost** [comment]
Some packages require PHP 8.2 or above so change your PHP to 8.2

**Comment by ehsanmim** [comment]
You are right the problem is solved.
