### ISSUE TITLE
Laravel Fortify configuration with config file & ServiceProvider

### ISSUE THREAD

**Issue by emrecanful** [opensheetorg/opensheet#8]

**Comment by emrecanful** [comment]
@ehsanmim @SudoFrost Please review this commit and share your ideas.
What has been done:
- Fortify configuration
-  Updated `app/Actions/Fortify`/CreateNewUser.php` and `PasswordValidationRules.php` according to our needs.
- New middleware `EnsureProfileDataFilled` has beed added. We have a model and migration named `Profile` which contains user's profile data like `birthdate`, `about`, `location` etc. These data should be filled in order to create a profile and use all of the functionalities of the OpenSheet. It has One-to-one relation with `User` model. If the user does not have a `Profile` resource record than after login all the pages protected by `auth` route middleware will redirect the user to initial profile form.
- `MustVerifyEmail` trait has been defined for the `User` model resource.
- Fortify default authentication workflow route views has been defined inside the `app/Providers/FortifyServiceProvider.php` file. Please refer to these Inertia responses in order to develop the front-end of these pages. If the paths are not suitable than these paths could be changed through this service provider php file.

**Comment by SudoFrost** [comment]
After reviewing your commit, everything looks good. However, I fixed a few spelling errors. I suggest changing "birthdate" to "birthday" in the profile.

**Comment by emrecanful** [comment]
@SudoFrost Good! Then I'll just close the issue.
