### ISSUE TITLE
Add  overtrue/laravel-follow & overtrue/laravel-like packages to the project & configuration

### ISSUE THREAD

**Issue by emrecanful** [opensheetorg/opensheet#9]
The links for the packages and the documentations:

- Like :: [overtrue/laravel-like](https://github.com/overtrue/laravel-like)
- Follow :: [overtrue/laravel-follow](https://github.com/overtrue/laravel-follow)

Please take a look at these packages if you haven't yet since the meeting.

Configuration hints:
- `Sheet`, `Timeland` model resources must be likeable by the `User` model resource.
- `Timeland`, `User` model resources must be followable by the `User` model resource.

**Comment by emrecanful** [comment]
The `overtrue` packages were added and the configurations were done according to the issue explanation.

!!ALSO!!
- Urgent bugfix: `MustVerifyEmail` Illuminate contract was defined as use trait BUT IT IS AN INTERFACE instead. The User model class has been fixed by replacing the `MustVerifyEmail` as "implements" to the class.
- Relationship classes were added multiple times. The duplicates were also removed.

**Comment by SudoFrost** [comment]
I checked the packages and they are great to start the project.

**Comment by emrecanful** [comment]
@SudoFrost  Good! Then I'll just close the issue.
